addons:
  apt:
    packages:
    - lftp
    - python-pygments
  ssh_known_hosts: hosting.pctsupport.hu
language: go
env:
  global:
  - secure: ZWgLEc1ACNsR7g2DfaavoVX8OXDSPwJXPwGih03rIngsthLK+ZDUjpIK7FMWok1GefCLsIMMQR6KFP2od9lKeRr2D8Tw8TZw92IwMpnsFVZnpx9laPPDwa0d05BDb754bZFxDNcz9oxGS6uBcN3izhAK+KjNl0oUfq2znjVhsifpiCxF4BkmUwAVeEL7j+elUr6OCoM/qNoRiak7dQr4OOnMv/sfOAlFsi/ugXDA7KIOW5CxPbl5kEziYr5zH5LMEikqor8RAJaHFo5ZNcBo946UEYCn9Lszh7/dCbVREqOA6ES70flyiJd4JbPwiGAuMaukebrUHVk3HBYL9SE4Yada2pPZbH/kD1LCwNFlCJRAp/CPsARtqXlY5UeYSvAMfMEQYuukS7bbqguvW1JGlOuTI04hq+G6Xyuzau751uRpjzLlsv0oW9B+MbaDjAVW8FB7mBD/6l2ODMnlnZJAOdSyTYjqrNwISZ+oXB78d1sYAX+TiVEvO9f+6ce2U1yY2Ppa9o+CzsFpwcJghpqhPIxGL2zELIqBerOEHn5TG0gGZSFh8UA/42U5c63zrUfDGaIpfG7DUngeQ3YschqPZrZR9esf0tyAouzrN2Hte1aSdB0X84ItwZzy2vsHS3RkYxlFQzEbzuc/Bs8dfWGhlqmykiwY5eNn1EnvtiQJz7w=
  - secure: KmqbfsasJHOOXEG7k8I9H39SgJzw7bSdYYBAQcO2Em/E82kCnxwVWAEoXjAR5RtI1xE0o02WsSRehLXFl8VODwAmgBXHNyvD1476Efq5cOSAPC4ovhKWTMs8RS6DpMj8Pd9IiAU42re2rBos8p/70/PvPHUVEel3an3zao1rtUuQ46eBHcH/Bs3PFixnliu6gtpK8s1eBFhAAmzMm3Tdp+Fd7PZdVsqDVzr3oc5pvtQb+p/4GzmrR/9OldLfQvtiiy3PXGT8TTo8mG32wdaV0DrpXro727IPMVt6OM+elrjFrCNriJfpUjJFmuz/h48g2wvcL+ulLH3Y7miww89q4Ki80tgs4Gvd115z/ehOkeWX9iImGMjfIJJctdf772Kbr3+ISoorom5QVrR0HbmcmoITBNJk8iMDjjeQvfgWC682t2ftK+l0QxjUF/iFZknzRrprpvyJRvng4ETmvXOx5bTVo0bOYuCYqXOcX+bSBMt0joI6wIMmBIsZ5EGcGUb7Dw8RM5M6431sEp+8/X3CAyHSyIi6NLnOSDwEk2Ej0GXsPzIOwzgOCgdVTX0bSvaVPEc7QjME/A641thYqHZtKg2/866DopVA2zk4StiipV7rZ5kAMqrqyKT3stj7CtJ49VSM2i1DtU6CA4K+qYDEDL1YDwiPRr5tYdo6ZKGP9Lo=
  - secure: fIWOArObSF3j+I04uXtW7R9Bc2AraqxPp6o6zt+KSzK08K/mKejFboLZW9ls13DOOqMijCvE82c/grfrLFnMxGVzD4XSW1QP4fN6mOmqDUyCnWQ5DPLLozNnR7th1dxVNIl2IpaGX+++uON/Dz0kSYh2SZ4N0HHFJ/Ilo3UmnZDup2t9PKlXAFxM/dEe6+vCwPktbyBxsRtU/ZZWlasy9znd0+CtjiJp58NBNXbia04WxgIRME7yXmNyk2b9U58fu5iomcqckABU1uv0Z9d/wWf2PZbvX/fGm5NUXD1G4ba8RgIISqch/mGQizBMnD/EDkC3WRP1L5jDkEfwERXY9eDynW4BZJi1KWh1omAYqMCWLky2uK3xCTqpNjau+5v2//5RAtc5FYn1uYlV4ABfeR2le0sOcxv9TDKibvrTvq2WD+Mt9ySHAuoPjPNdogRIDMTzCk01ObHU9L9kMvz499opJzDcL2iEti3kdvBAzyuNKOARMa+fUri8WC+YyXJKmsVlkFEF2UuPJ+TtVtxq5XaE+ql1qalGfSFGtlMwZPXEg8XIMKmoiugUzT29cVyUKEcox92LSpsBHtbCn5aDG+6RRfaWf6rujykynIwRW/8XKn6NtTyfVQNDe6HZxP6Klprlp61J7pZ2XP8Sq/T9jR5eEQCjRGtIrtFA3IJglgE=
install:
- rm -rf public || exit 0
- curl -LO https://github.com/gohugoio/hugo/releases/download/v0.62.0/hugo_extended_0.62.0_Linux-64bit.deb
- sudo dpkg -i hugo_extended_0.62.0_Linux-64bit.deb
script:
- git clone https://github.com/hgspsz/theme.git tmp
- cp -r tmp/* ./
- rm -r -f tmp
- hugo
after_success: 
- cd public && lftp -e "set ftp:ssl-allow no; cd ./public_html; mirror -R .; ls; exit" -u $FTP_USER,$FTP_PASSWORD sftp://harsanyisportpszichologus.hu
